### ISSUE TITLE
[  错误  ]:输入链接有误！无法获取 id 

### ISSUE THREAD

**Issue by echihx** [imgyh/tiktok#10]
TikTokCommand.exe 有问题
几天前还可以，但现在出现错误：
[  错误  ]:输入链接有误！无法获取 id 

我输入的网址是: 
https://v.douyin.com/xxxx
https://www.iesdouyin.com/share/note/xxxx

**Comment by imgyh** [comment]
具体链接是什么呢

**Comment by echihx** [comment]
这是我试过的一些链接
https://v.douyin.com/SgVYj47/
https://v.douyin.com/Sp1AMge/

**Comment by imgyh** [comment]
> 感谢修复，现在我可以使用了。 但似乎该exe文件存在误报警告？ 当我尝试下载时，Windows Defender和Chrome 都进行了拦截。

报什么警告，下载exe时报风险警告还是程序有问题，exe下载报风险的话放行就好了，应该是误报

**Comment by imgyh** [comment]
> 感谢修复，现在我可以使用了。 但似乎该exe文件存在误报警告？ 当我尝试下载时，Windows Defender和Chrome 都进行了拦截。

报什么警告，下载exe时报风险警告还是程序有问题，exe下载报风险的话放行就好了，应该是误报
