### ISSUE TITLE
Windows Defender和Chrome 误报警告?

### ISSUE THREAD

**Issue by echihx** [imgyh/tiktok#11]
感谢修复，现在我可以使用了。:D

但似乎该exe文件存在误报警告？
当我尝试下载时，Windows Defender和Chrome 都进行了拦截。

**Comment by imgyh** [comment]
报什么警告，下载exe时报风险警告还是程序有问题，exe下载报风险的话放行就好了，应该是误报

**Comment by echihx** [comment]
两个图像链接我试过给错误:
https://v.douyin.com/SGf8jMb/
https://v.douyin.com/SGmB1Lo/

我也尝试了其他链接，但只有这两个有问题

[  提示  ]:正在请求的作品 id = 7210935713947290895
[  错误  ]:保存 result.json 失败
[  错误  ]:下载出错
...

[  提示  ]:正在请求的作品 id = 7210330045691252026
[  错误  ]:保存 result.json 失败
[  错误  ]:下载出错
...

**Comment by imgyh** [comment]
好像是程序里面文件夹名字没处理好，有非法的字符，保存出错了，我这里直接那个文件件打不开。有空了我解决一下
