### ISSUE TITLE
麻烦问一下，直播信息无法解析

### ISSUE THREAD

**Issue by xxdahai** [imgyh/tiktok#12]
在执行：TikTok.py中的“getLiveInfo()”函数时没有有效的数据返回，这里做一个简单整理：
1、“getLiveInfo”中有一行代码：`response = requests.get(live_api, headers=self.headers)`，其中“live_api”是`https://live.douyin.com/webcast/room/web/enter/?aid=6383&device_platform=web&web_rid=7211132036965387065&X-Bogus=DFSzswSLf0sANnEftcWkPU9WcBJk`；“self.headers”是`{'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36', 'referer': 'https://www.douyin.com/', 'Cookie': 'msToken=G51G24=k3Vq41d=FWwlKDNEs0dmQ3i1LvMd8XyYVO=hq9lGY0Lct3ErhQS8iY6AwuPphlNtl5Dg5pqQKl87AhKNOtRfNwVUyRciGSkivu0I; ttwid=1%7C-_gmNNKV_riWyBfznI1MGhTpLL4sGRGBuWNWlMCkApM%7C1679017410%7C40a36c2dc5f75118302b874e941db55309148ab5de930e4a893d738397a37bc9; odin_tt=324fb4ea4a89c0c05827e18a1ed9cf9bf8a17f7705fcc793fec935b637867e2a5a9b8168c885554d029919117a18ba69; passport_csrf_token=f61602fc63757ae0e4fd9d6bdcee4810;'}`；个人目测这两个参数的值没有什么错误；
2、“getLiveInfo”执行“requests.get”后，“response.text”的值却是`{"extra":{"now":1679017411116},"status_code":4001038,"data":{"prompts":"该内容暂时无法无法查看"}}`；不知道是哪个环节出现了问题，麻烦您不忙的时候看一下，非常感谢。
3、“live_api”中的“web_rid=7211132036965387065”在当前时间`2023-03-17 09:58`是有效的，我在手机上正在看直播，在用网页打开对应的分享链接[https://v.douyin.com/SnXMoh2/](https://v.douyin.com/SnXMoh2/)时，抓包返回的“web_rid”也是7211132036965387065。

**Comment by imgyh** [comment]
![QQ截图20230317100439](https://user-images.githubusercontent.com/47165525/225793479-aef12c63-b0b5-4ed6-81fc-82ab71a591a4.jpg)
用这个链接来解析, 后面看怎么把分享链接转化过来

**Comment by imgyh** [comment]
https://live.douyin.com/208823316033 
用网页中这个地址来解析

**Comment by xxdahai** [comment]
哦，我根据“TikTokCommand.py”的写法`key_type, key = tk.getKey(url)`，提示`[  错误  ]:输入链接有误！无法获取 id`，所以就不知道是应该用哪个值了， 我试了一下，“[208823316033](https://live.douyin.com/208823316033)”可以正常解析
