### ISSUE TITLE
接口未返回数据, 正在重新请求!

### ISSUE THREAD

**Issue by zwping** [imgyh/tiktok#15]
大佬，这个有办法过吗？猜测验证码问题

<img width="809" alt="image" src="https://user-images.githubusercontent.com/26704739/227706353-c047bdf4-4c55-4d0e-b909-ab79230d77bb.png">

**Comment by SymbolAction** [comment]
+1

**Comment by wanglihuaya** [comment]
+1

**Comment by imgyh** [comment]
![image](https://user-images.githubusercontent.com/47165525/227718371-f08eca1c-e792-46ba-9e9a-65ad4d88c6cd.png)

稍后更新，更改一下referer就好了

**Comment by wanglihuaya** [comment]
六，坐等大佬更新
