### ISSUE TITLE
昨晚更新后，新的版本下载目录 改变了

### ISSUE THREAD

**Issue by wanglihuaya** [imgyh/tiktok#20]
先说一句大佬牛逼，连夜改BUG，辛苦了
我遇到的问题就是，昨晚更新后，新的版本下载目录 改变了，能不能和之前一样，去掉外面的 user/post 目录，我使用的是cmd:  --cmd true -M post --link https://v.douyin.com/SDvGuAm/ --path /path/... --music false --cover false --avatar false --cookie "msToken:B1..."
![image](https://user-images.githubusercontent.com/49522285/228401917-a8e06770-2e78-4777-a404-f91ceb1f944f.png)

**Comment by imgyh** [comment]
这个目录结构是为了区分多个链接多种模式，你可以把以前下载的复制到post里面去，后面就不会重复下载了

**Comment by imgyh** [comment]
你有什么建议都可以提，大家都来来当产品经理，哈哈哈哈

**Comment by wanglihuaya** [comment]
> 这个目录结构是为了区分多个链接多种模式，你可以把以前下载的复制到post里面去，后面就不会重复下载了
