### ISSUE TITLE
下载个人主页视频，似乎不能自动翻页？只能下载33条

### ISSUE THREAD

**Issue by wanglihuaya** [imgyh/tiktok#21]
还有个问题是 下载个人主页视频，似乎不能自动翻页？只能下载33条，请求第一次33条，之前是20条，然后第二次就超时了，最后就开始下载第一次请求的33条数据了
![image](https://user-images.githubusercontent.com/49522285/228402321-e630fdc7-c44a-44f7-b74d-c7b174bc207d.png)

**Comment by zhangya4548** [comment]
而且我发现如果一个主页只有几个视频,也是获取不到数据,感觉抖音的这个主页数据接口很奇怪

**Comment by wanglihuaya** [comment]
> 而且我发现如果一个主页只有几个视频,也是获取不到数据,感觉抖音的这个主页数据接口很奇怪

这次改的，真的太恶心了

**Comment by imgyh** [comment]
请求的链接发一下，我去看看怎么回事

**Comment by wanglihuaya** [comment]
/usr/bin/python3 /TikTokCommand.py --cmd true -M post --link https://v.douyin.com/SDvGuAm/ --path /media/path/ --music false --cover false --avatar false --cookie "msToken:B1TPA_..."

**Comment by imgyh** [comment]
> ```
> /usr/bin/python3 /TikTokCommand.py --cmd true -M post --link https://v.douyin.com/SDvGuAm/ --path /media/path/ --music false --cover false --avatar false --cookie "msToken:B1TPA_..."
> ```

![image](https://user-images.githubusercontent.com/47165525/228412798-3ae3e087-ad73-4ebe-b44e-d9135b54d7cc.png)
能翻页啊，你把cookie中的冒号改成等号呢，每一个键值对后面需要加分号和空格，这几个都加进去了吗

```
"msToken=xxx; ttwid=xxx; odin_tt=xxx; passport_csrf_token=xxx; sid_guard=xxx;"
```

**Comment by wanglihuaya** [comment]
> > ```
> > /usr/bin/python3 /TikTokCommand.py --cmd true -M post --link https://v.douyin.com/SDvGuAm/ --path /media/path/ --music false --cover false --avatar false --cookie "msToken:B1TPA_..."
> > ```
> 
> ![image](https://user-images.githubusercontent.com/47165525/228412798-3ae3e087-ad73-4ebe-b44e-d9135b54d7cc.png) 能翻页啊，你把cookie中的冒号改成等号呢，每一个键值对后面需要加分号和空格，这几个都加进去了吗
> 
> ```
> "msToken=xxx; ttwid=xxx; odin_tt=xxx; passport_csrf_token=xxx; sid_guard=xxx;"
> ```

我试下

**Comment by wanglihuaya** [comment]
> > > ```
> > > /usr/bin/python3 /TikTokCommand.py --cmd true -M post --link https://v.douyin.com/SDvGuAm/ --path /media/path/ --music false --cover false --avatar false --cookie "msToken:B1TPA_..."
> > > ```
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/47165525/228412798-3ae3e087-ad73-4ebe-b44e-d9135b54d7cc.png) 能翻页啊，你把cookie中的冒号改成等号呢，每一个键值对后面需要加分号和空格，这几个都加进去了吗
> > ```
> > "msToken=xxx; ttwid=xxx; odin_tt=xxx; passport_csrf_token=xxx; sid_guard=xxx;"
> > ```
> 
> 我试下

Nice,改成等号就可以了。🙏

还有个 建议，我重新开个issue吧
