### ISSUE TITLE
遍历自动跳过时间好长

### ISSUE THREAD

**Issue by wanglihuaya** [imgyh/tiktok#24]
遍历获取个人主页所有视频的时候，下载过的，会自动跳过，视频数目比较多的时候，比如几百个，判断是不是存在 这个时间有点长，这个能不能通过什么方式优化一下 😗

**Comment by imgyh** [comment]
这个可能需要用到数据库记录哪些下载了的，哪些是没下载的，现在把文件名在windows下出错的问题解决了，就加入数据库吧。(我测试文件名不能太长，以前是80个字符，现在我改成20个字符好像不报错了，文件名也不加入其他符号了，只用数字字母汉字)

**Comment by wanglihuaya** [comment]
> 这个可能需要用到数据库记录哪些下载了的，哪些是没下载的，现在把文件名在windows下出错的问题解决了，就加入数据库吧。(我测试文件名不能太长，以前是80个字符，现在我改成20个字符好像不报错了，文件名也不加入其他符号了，只用数字字母汉字)

Nice,根据名字归类的 确实显示的名字好长🥲，我用shell脚本自己操作一下也中

保存数据至数据库，我看是在TODO里面，大佬有时间就整一下吧🤩

**Comment by wanglihuaya** [comment]
在本地生成一个list.json 可以吗，不过好像也是，和操作数据库差不多了
