### ISSUE TITLE
大佬  不可以下载tiktok的视频吗

### ISSUE THREAD

**Issue by namedssy** [imgyh/tiktok#35]
python3 TikTokCommand.py -C True -l https://www.tiktok.com/@mikkyklayker/ -p /Users/ShiyuShao/Downloads/down --cookie "ttwid=1|GvLWe8xFjTDY-N4dzX1r9SkTuM7_mwKwAOlN64DsneA|1682241910|8313d92eaa8b1834a7b6b877420c0ca0da7789f10113530ca6779adb0066ff0e; tiktok_webapp_theme=light; tt_csrf_token=1Z8jEE7G--opWf32bZ_MdWEwszm50UX5msl0; tt_chain_token=M6/syAwhBbGBN240rOCA6Q==; __tea_cache_tokens_1988={"_type_":"default","user_unique_id":"7225173950042342958","timestamp":1682241946416}; passport_csrf_token=e2dd5ed470cbc744195c3a32557ffd0b; passport_csrf_token_default=e2dd5ed470cbc744195c3a32557ffd0b; s_v_web_id=verify_lhbl0zcx_iPPtH8vB_xrqE_4WYu_9Q5p_g7OQaFOPqLPO; cmpl_token=AgQQAPNSF-RO0rRtIViDdN0T_iVgXuMxP6zZYM-Buw; sid_guard=20e3f55b946dc8ef03063cf5aab05fac|1683353225|15551999|Thu,+02-Nov-2023+06:07:04+GMT; uid_tt=b1028fa343c03afd2effe21f297ab794f3a215c3a51bbb2c9aee3c3d3b3009a8; uid_tt_ss=b1028fa343c03afd2effe21f297ab794f3a215c3a51bbb2c9aee3c3d3b3009a8; sid_tt=20e3f55b946dc8ef03063cf5aab05fac; sessionid=20e3f55b946dc8ef03063cf5aab05fac; sessionid_ss=20e3f55b946dc8ef03063cf5aab05fac; sid_ucp_v1=1.0.0-KGJkOWMzOWRiNGY3NDM2YzAwMDkwODExNzAzZTJmY2YwNjI5MDMzNDgKIAiqiJja8P_zqWQQid3XogYYswsgDDDCoc-iBjgHQPQHEAQaB3VzZWFzdDUiIDIwZTNmNTViOTQ2ZGM4ZWYwMzA2M2NmNWFhYjA1ZmFj; ssid_ucp_v1=1.0.0-KGJkOWMzOWRiNGY3NDM2YzAwMDkwODExNzAzZTJmY2YwNjI5MDMzNDgKIAiqiJja8P_zqWQQid3XogYYswsgDDDCoc-iBjgHQPQHEAQaB3VzZWFzdDUiIDIwZTNmNTViOTQ2ZGM4ZWYwMzA2M2NmNWFhYjA1ZmFj; store-idc=useast5; store-country-code=us; store-country-code-src=uid; tt-target-idc=useast5; tt-target-idc-sign=ERT4CjkZDlFYLg4UcS9H31IVNShUOcrR6ajkRKz0Zq_HqqdIFIu6Qes7JJVLw5reQVnVFuWRXXTcAFI1hV4gl6jEH-l4VyxSpiT143ZxrKYVL6m8PoQFXuhDroZpoEl6RdW05_X3qBxnivhYPzAYDJoPIeFXIUgM1Uf7yK19l6t1LIP1UISrxAnp--94csSy9i1vpTwKUZgc1bD-7hfGS0juZuGUIalF99G2xpw2QASgASPnctClIXi4qIT1EIMBDgrT6iICyKXdCIznj8EiUhRu1tRdAZdl81lpPCIvORUvHfIU7hqkkfsBzBfastZBj_bBC7EIW5b9ZBLSUFCIJMItbYDulop4leBYVZ4dRy5L5lTYUaTAL8lYWfoJkthmaIEQUvLepYEHtS7rFbzA4yAf_JSegWT_NPJtRqLoT53ZwfkaiM7pJSlwVys7Ab01yRXoujEnUtiW_HWM2mHipnVmbJb7HJYgcz0WcFybkhMGgOGCilRfN2XLHBUxY-0A; csrf_session_id=96ea20c5f52bb806508a6e138e1c6564; passport_fe_beating_status=false; ttwid=1|GvLWe8xFjTDY-N4dzX1r9SkTuM7_mwKwAOlN64DsneA|1683353745|795f738013dc8c4ae04b9c3525af5d3d8cd2cb27ba1aba2e49f837e0c0447793; odin_tt=31a19dad79f55d18a86d37b3b9ecb1cc84c3f05221b963354f82764d5b0ba2ea6ebf41440b26cecf91a900a4cdb479c04bf677d818d0ff61f4dcff04eb49a466d0bc46d7243dc44424c55033567e6dbf; msToken=GTKWOA944qdAmlDNY-gBTZ0FHoTUw_t7MEWFt8m2p8M9HnZkuLZqo1eKVThdIQbG6aqsIpMjLQMz772HMpdaFtpp-3d90TIyFHPKaYTbrs1Cr8lnMB9i0MA7losft2Z7oQ==; msToken=3MibmsPbmGbgWDcRwItkXCDJUtMxHLetf-uuDSdgWubaIWlgMZRczfboH_BuMeBbTRi9AL4JGeOrlGv5egJzXffPnPWfOiWGNxukCstg2T_2aWO9uBsL"
[  提示  ]:数据保存路径 /Users/ShiyuShao/Downloads/down
--------------------------------------------------------------------------------
[  提示  ]:正在请求的链接: https://www.tiktok.com/@mikkyklayker/

[  错误  ]:输入链接有误！

[下载完成]:总耗时: 0分钟4秒

**Comment by imgyh** [comment]
暂时不支持

**Comment by namedssy** [comment]
好的谢谢回复~   [TikTokDownload](https://github.com/Johnserf-Seed/TikTokDownload)  是不是也不能下载 tiktok的视频啊

**Comment by imgyh** [comment]
是的现在只能支持抖音

**Comment by namedssy** [comment]
3q~
