### ISSUE TITLE
增量更新问题

### ISSUE THREAD

**Issue by amsteel** [imgyh/tiktok#37]
发现异常中断后（网络问题，主机意外重启等），没有下载完成的视频只有空目录， 没有文件。 但是在增量下载模式下，这些都会被认为是已经下载完成的。

批量下载数量多的时候，这个手动查找和下载比较麻烦。

能解决一下吗？

谢谢大神！

**Comment by imgyh** [comment]
感谢反馈，确实没考虑到这个问题，后面修复

**Comment by amsteel** [comment]
是不是把记录从数据库里删了，增量会重新下载了？怎么才能把文件夹和数据库记录联系起来？如果有办法的话，目前也可以手工搞一下。

**Comment by imgyh** [comment]
你可以看一下大概有多少个视频没有被下载，用--xxxnumber 参数指定下载前多少个，不用加增量更新的代码，下载完后，如果作者有更新，可以继续使用增量更新下载新发布的作品

**Comment by amsteel** [comment]
没下载的视频可能在列表的中间，不一定是最后。
下载多个合集：不用修改yaml的情况下， 设置 --mixnumber 12345 和 --allmixincrease False
是不是这样应该就可以？

**Comment by imgyh** [comment]
要么你修改yaml，要么用命令行，设置 --allmixnumber 12345 和 --allmixincrease False

**Comment by imgyh** [comment]
删除数据库也可以，你没有下载的视频记录删除就好了，全部合集的话要secuid有值的，secuid为空的是单个合集的

**Comment by amsteel** [comment]
> 要么你修改yaml，要么用命令行，设置 --allmixnumber 12345 和 --allmixincrease False

这个测了没问题。这样就不用弄数据库了。 目前发现唯一的问题就是出现意外， 有时候存的视频文件大小不对。这个好像不是太好查，目前就是把特别小的文件删了，再重新下载。

谢谢大佬！
