### ISSUE TITLE
127.0.0.1:5000/douyin/user/post 这个网页版的接口是不是挂了

### ISSUE THREAD

**Issue by emmIsabella** [imgyh/tiktok#40]
一直返回500，我用的是你搭建的，一天也就请求几次而已，不至于打崩了吧

**Comment by imgyh** [comment]
我可以用你看你参数带全没有

**Comment by imgyh** [comment]
> { "share_link": " https://www.douyin.com/user/xxxxxxxxx ", "cursor":0 } 这种，之前都是可以用的

我readme里面不是这样写的吧，你仔细看看
