### ISSUE TITLE
账户注销会造成死循环

### ISSUE THREAD

**Issue by fly1000000** [imgyh/tiktok#8]
测试url：https://v.douyin.com/S53TFTV/，非登陆状态显示私密账号，然后会进入while true的死循环逻辑

我在之前while true上加了如下类似的逻辑能用了， 期待更新

i = 0
while i < 3:
    # 接口不稳定, 有时服务器不返回数据, 需要重新获取
    try:
        .......
    except Exception as e:
        i = i + 1
        print("[  警告  ]:接口未返回数据, 正在重新请求!\r")
if i >= 3:
    print("[  警告  ]:账户可能关闭\r")
    break

**Comment by imgyh** [comment]
> 测试url：[https://v.douyin.com/S53TFTV/，非登陆状态显示私密账号，然后会进入while](https://v.douyin.com/S53TFTV/%EF%BC%8C%E9%9D%9E%E7%99%BB%E9%99%86%E7%8A%B6%E6%80%81%E6%98%BE%E7%A4%BA%E7%A7%81%E5%AF%86%E8%B4%A6%E5%8F%B7%EF%BC%8C%E7%84%B6%E5%90%8E%E4%BC%9A%E8%BF%9B%E5%85%A5while) true的死循环逻辑
> 
> 我在之前while true上加了如下类似的逻辑能用了， 期待更新
> 
> i = 0 while i < 3: # 接口不稳定, 有时服务器不返回数据, 需要重新获取 try: ....... except Exception as e: i = i + 1 print("[ 警告 ]:接口未返回数据, 正在重新请求!\r") if i >= 3: print("[ 警告 ]:账户可能关闭\r") break

感谢反馈，既然是私密账号，那肯定是下载不了的。你登录之后能看到这个博主发的视频吗?

**Comment by fly1000000** [comment]
这个账号应该是关注之后才能看到， 我是关注者，登录之后能看到，那就是私密账号会造成死循环～

**Comment by imgyh** [comment]
> 这个账号应该是关注之后才能看到， 我是关注者，登录之后能看到，那就是私密账号会造成死循环～

如果要下载的话，可能得用你的账号登录之后的cookie，这样才能下载下来，我后面在研究一下登录的方法吧，直接用你们自己的cookies，但是这样下载过多可能有封号的风险

**Comment by imgyh** [comment]
这个死循环我优化一下，一直不反回数据多少秒之后就抛异常退出

**Comment by fly1000000** [comment]
嗯嗯

**Comment by imgyh** [comment]
> 另外你使用的时候， 有报过， TypeError: Cannot read property 'JS_MD5_NO_COMMON_JS' of null 这个错误吗，看去来是X-Bogus.Js中没有定义JS_MD5_NO_COMMON_JS
> 
> 但奇怪的是，我的mac环境没事， 但ubuntu上会有这个错误

我ubuntu装的node环境，没有遇到过这个错误，试一下node全局装一下md5这个包呢

**Comment by imgyh** [comment]
你这个报错是从哪儿来的，我那个程序报错异常应该捕获了的啊，他会去请求远程部署的x-bogus接口啊

**Comment by fly1000000** [comment]
见鬼了， npm install md5-node --save， npm install md5， 都安装了 依然是这个错误，感觉哪里的姿势不对

**Comment by imgyh** [comment]
> 见鬼了， npm install md5-node --save， npm install md5， 都安装了 依然是这个错误，感觉哪里的姿势不对

你先直接去用node执行那个js文件试试呢，看报什么错误
