### ISSUE TITLE
X-Bogus.js本地调试时出现错误：引用错误: module 未定义

### ISSUE THREAD

**Issue by xxdahai** [imgyh/tiktok#9]
我在进行本地调试的时候，没有使用python环境，使用的是googleV8环境，调试时提示：引用错误: module 未定义，能否麻烦您帮忙完善一下，非常感谢。

**Comment by imgyh** [comment]
能说详细点吗，我这儿用的Python的execjs这个库来调用本地机器上的js环境执行x-bogus.js，从而获取的加密参数

**Comment by xxdahai** [comment]
在加载js代码的时候，第563行报错，ReferenceError: module is not defined（引用错误: module 未定义
），这个问题不单单是用googleV8引擎，我随机在网上找了一个在线js调试网站也是报这个错误，我猜测应该是python的execjs库在执行的时候加载了一些标准库，从而定义了“module”。
[http://www.wetools.com/js-run](url)，这是我找的在线调试网站。
第563行代码：
`module.exports = 
    sign
  };`
尝试找了一些方法替代 module.exports 均失败了。

**Comment by imgyh** [comment]
用node环境试试呢，node环境用着没问题

**Comment by xxdahai** [comment]
我仔细查了一下：module.exports 的意思是将 sign 共享到外部进行使用，这个是node.js的一个特性，我作为本地调试的话并不需要进行共享操作，所以我将`module.exports = { sign };`代码删除掉以后即可正常解析了。
